theme: jekyll-theme-cayman
title: "A tool to automatically infer columns data types in .csv files"
description: "A parallel implementation of Schema inference using python"
author: "Ramses Alexander Coraspe Valdez"
